### ISSUE TITLE
Would this method work for any configuration?

### ISSUE THREAD

**Issue by mwagg22** [haxpor/sdl2-cimgui-demo#1]
Following your method in your blog this should work for vulkan with sdl as well? I just have to configure the sdl header , build dll and link this bad boy to my main project.

**Comment by haxpor** [comment]
Yes, the similar approach should work the same although I didn't test with vulkan. I'm looking at [SDL + Vulkan](https://github.com/ocornut/imgui/blob/master/examples/example_sdl_vulkan/main.cpp) example of imgui, it includes both implementation files of SDL and Vulkan (similarly to what I have done in this repo).

Just make sure we bring in all requires implementation files, you should be fine :)

**Comment by mwagg22** [comment]
Cool thanks!!
